---
Name: docs
After: framework/routes#coreroutes
---
Director:
  rules:
    'dev/docs//$Lang/$Action': 'DocumentationViewer'
    'DocumentationOpenSearchController//$Action': 'DocumentationOpenSearchController'
