---
Name: docs
After: framework/routes#coreroutes
---
Director:
  rules:
    'dev/docs//$Action/$ID/$OtherID': 'DocumentationViewer'
    'DocumentationOpenSearchController//$Action': 'DocumentationOpenSearchController'
